name: Build APK and unsigned IPA

on:
  workflow_dispatch:

jobs:
  build-android:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version-file: pubspec.yaml

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: |
        flutter build apk --release
        mv build/app/outputs/flutter-apk/app-release.apk build/Mobylote-release.apk

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: mobylote-android-release
        path: build/Mobylote-release.apk

  build-ios:
    name: Build IPA
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version-file: pubspec.yaml

    - name: Set up Ruby for iOS builds
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Install CocoaPods
      run: sudo gem install cocoapods

    - name: Install dependencies
      run: flutter pub get

    - name: Install iOS dependencies
      run: |
        cd ios
        pod install
        cd ..

    - name: Build IPA
      run: |
        flutter build ios --release --no-codesign
        mkdir -p build/ios/unsigned/Payload
        mv build/ios/Release-iphoneos/Runner.app build/ios/unsigned/Payload/Runner.app
        cd build/ios/unsigned
        zip -r Runner.zip Payload
        mv Runner.zip Mobylote-release.ipa

    - name: Upload unsigned IPA
      uses: actions/upload-artifact@v3
      with:
        name: mobylote-ios-release
        path: build/ios/unsigned/Mobylote-release.ipa
